spring.application.name=backend
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=visitsecure29@gmail.com
spring.mail.password=uhco zaea hthq phxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
cloudinary.cloud_name=dnafiaiq0
cloudinary.api_key=972869237146572
cloudinary.api_secret=wwaAuH4S9siaBPD0Lc0stylcnAA